main:
  # - identifier: blog
  #   name: Blog
  #   title: Blog posts
  #   url: /blogs
  #   weight: 1
  - identifier: galleries
    name: Fotky
    title: Galérie fotiek
    url: /galleries
    weight: 2
  #   #Dropdown menu
  #   # - identifier: dropdown
  #   #   title: Example dropdown menu
  #   #   name: Dropdown
  #   #   weight: 3
  #   # - identifier: dropdown1
  #   #   title: example dropdown 1
  #   #   name: example 1
  #   #   url: /#
  #   #   parent: dropdown
  #   #   weight: 1
  #   # - identifier: dropdown2
  #   #   title: example dropdown 2
  #   #   name: example 2
  #   #   url: /#
  #   #   parent: dropdown
  #   #   weight: 2